### ISSUE TITLE
Notification "Iitem added" not working 

### ISSUE THREAD

**Issue by QQsha** [RomainPierre7/jellyfin-plugin-TelegramNotifier#10]
The notification "Playback start" working, there is no problem. 
But I don't get notifications for new episodes and seasons.
Verison: 10.9.10.2

**Comment by QQsha** [comment]
Nevermind, got it after 1 hour delay

**Comment by RomainPierre7** [comment]
Hello,

The item-added notifier alerts you when the item's metadata has been fully gathered. Depending on your connection and providers, there may be a slight delay. Additionally, please verify that the timer for the scheduled task is correctly set to 30 seconds or 1 minute.

Thank you for using the plugin! If you find it valuable, please consider giving it a star 🌟 It helps others discover it too!
