### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by Atosmanic** [RomainPierre7/jellyfin-plugin-TelegramNotifier#12]
I get no messages about new movies

**Comment by RomainPierre7** [comment]
Hello,

Please give more details. Otherwise I can't help you. If the plugin is correctly set up, you will be notified when Jellyfin successfully collects the movie metadata.

**Comment by Atosmanic** [comment]
Have you telegram?

________________________________

**Comment by Atosmanic** [comment]
settings are good but when i click on scan libary then i got no message about new videos

**Comment by RomainPierre7** [comment]
Does the metadata of the movie be collected ? Also in the scheduled task you can run the item added telegram notifier and check if it is correctly set up to run every minute. Also check that you have correctly set up the item added options:

![Screenshot_2024-10-24-00-19-37-32_4b95a63cd60fd3e0f30739d89812bf6c.jpg](https://github.com/user-attachments/assets/d0115a72-2522-4714-b3a8-10167aef6c0e)

**Comment by Atosmanic** [comment]
If i click  manual on item added notifier them it works but why is this not automated?Verstuurd vanaf mijn iPhoneOp 24 okt 2024 om 00:20 heeft Romain PIERRE ***@***.***> het volgende geschreven:﻿
Does the metadata of the movie be collected ? Also in the scheduled task you can run the item added telegram notifier and check if it is correctly set up to run every minute. Also check that you have correctly set up the item added options:
Screenshot_2024-10-24-00-19-37-32_4b95a63cd60fd3e0f30739d89812bf6c.jpg (view on web)

**Comment by RomainPierre7** [comment]
It's automatic, of course. Click on the task and check that it's scheduled every minute. Example:

![Screenshot_2024-10-24-00-36-03-80_4b95a63cd60fd3e0f30739d89812bf6c.jpg](https://github.com/user-attachments/assets/6f3237fc-fa44-4b22-a089-04e09093a4e2)
