### ISSUE TITLE
Couldn't parse ISO 8601 date string '2024-10-01 00:00:00'

### ISSUE THREAD

**Issue by gioxx** [RomainPierre7/jellyfin-plugin-TelegramNotifier#13]
Ciao. I am trying to install the plugin on my Jellyfin (Debian-based) machine. I get this error:

```
Error

Couldn't parse ISO 8601 date string '2024-10-01 00:00:00'

o@https://jellyfin.contoso.com/web/main.jellyfin.bundle.js?f1238435f421c71ad785:2:301722
31746/en/<@https://jellyfin.contoso.com/web/plugins-plugin.3420d67af1391b068d1a.chunk.js:1:9626
en@https://jellyfin.contoso.com/web/plugins-plugin.3420d67af1391b068d1a.chunk.js:1:9435
hu@https://jellyfin.contoso.com/web/node_modules.react-dom.bundle.js?f1238435f421c71ad785:2:60311
xi@https://jellyfin.contoso.com/web/node_modules.react-dom.bundle.js?f1238435f421c71ad785:2:119252
bs@https://jellyfin.contoso.com/web/node_modules.react-dom.bundle.js?f1238435f421c71ad785:2:108506
vs@https://jellyfin.contoso.com/web/node_modules.react-dom.bundle.js?f1238435f421c71ad785:2:108434
gs@https://jellyfin.contoso.com/web/node_modules.react-dom.bundle.js?f1238435f421c71ad785:2:108295
as@https://jellyfin.contoso.com/web/node_modules.react-dom.bundle.js?f1238435f421c71ad785:2:105130
is@https://jellyfin.contoso.com/web/node_modules.react-dom.bundle.js?f1238435f421c71ad785:2:105512
Bl@https://jellyfin.contoso.com/web/node_modules.react-dom.bundle.js?f1238435f421c71ad785:2:46687
76067/rs/<@https://jellyfin.contoso.com/web/node_modules.react-dom.bundle.js?f1238435f421c71ad785:2:103087
```

**Comment by RomainPierre7** [comment]
Hello,

The parse function is not relative to the plugin but to the server directly. You're problem here is that 2024-10-01 00:00:00 isn’t quite in ISO 8601 format due to the space between the date and time. The correct ISO 8601 format would replace the space with a T: 2024-10-01T00:00:00.

Here’s the corrected string:

2024-10-01T00:00:00

**Comment by gioxx** [comment]
Ciao @RomainPierre7.
First of all, thank you for your response. What I am missing is what I am supposed to do. I am simply following these instructions: https://github.com/RomainPierre7/jellyfin-plugin-TelegramNotifier?tab=readme-ov-file#install-the-plugin

And, as I click on the Telegram Notifier icon in the catalog of available plugins, I immediately get the error I gave you just above.

Thanks 😄

**Comment by RomainPierre7** [comment]
Hello again @gioxx 

Jellyfin have indeed changed the way they handle the timestamp and I hadn't adapted the manifest accordingly. My apologies, I thought your error came from another parse. I've just corrected it to comply with the new ISO. 

I'll let you try again and let me know if it works for you now. You may need to remove and add the repository url a second time or restart your server.

**Comment by gioxx** [comment]
Great, @RomainPierre7, everything works perfectly now. 
Thank you very much for your help 😄

**Comment by RomainPierre7** [comment]
Glad it works @gioxx. Thanks to you for alerting me to the parser format change.

If you like the project, feel free to put a star on GitHub ⭐ to help others discover it. 

Have a nice evening !

**Comment by gioxx** [comment]
> If you like the project, feel free to put a star on GitHub ⭐ to help others discover it.

Already done it! Thanks again! 😄
