### ISSUE TITLE
"Item Added" could have more options to avoid too much notifications.

### ISSUE THREAD

**Issue by Maphra** [RomainPierre7/jellyfin-plugin-TelegramNotifier#3]
By default, "Item Added" generates notifications for episodes, seasons, and the entire TV show. It would be awesome to have a more granular configuration option for this event.
![image](https://github.com/RomainPierre7/jellyfin-plugin-TelegramNotifier/assets/108915704/8077694e-2298-4e51-b2e0-d2bc47803ca6)

**Comment by RomainPierre7** [comment]
Sure, I will plan to do it within the next few days and notify you here when the new release will be available ;)

**Comment by RomainPierre7** [comment]
The update is available ([release](https://github.com/RomainPierre7/jellyfin-plugin-TelegramNotifier/releases/tag/10.9.4.0)), and you can now choose to be notified about each category (movies, series, season, episodes) separately. Your server will update within 24 hours, but you can force it from Dashboard => Scheduled tasks => Update plugins.

If you like this project and find it useful, don't forget to give it a star. It helps others to discover it. Thank you ;)

If you find a bug, don't hesitate to open an issue again. Testers are welcome !

**Comment by Maphra** [comment]
Not sure if this comment will reopen the issue, but I really need to thank you. I didn't have many expectations, but you really did it. You were very polite and even gave me some tips to update the plugin in the Jellyfin. Thank you so much, and keep up the good work! :)

**Comment by RomainPierre7** [comment]
I really appreciate it, thank you. Glad you like it !
