### ISSUE TITLE
didn't get a notification on telegram

### ISSUE THREAD

**Issue by fit206** [RomainPierre7/jellyfin-plugin-TelegramNotifier#4]
I want to ask how to set auto added movie notification from jellyfish to telegram channel. Or maybe you can provide a way in the form of a video to make it easier for users. Maybe I have the wrong setting because I don't get notifications from jellyfin to telegram. Please help me..

**Comment by RomainPierre7** [comment]
Hi,

Did you correctly set the server ip, the bot token and the chat ID ? If it's the case when you press the test button you normally receive a message on telegram and the test button turn in green. Is it the case ? Also is your server well connected to internet ?

Let me know and don't hesitate to add more details. If you share a screenshot of your settings don't forget to blur your telegram credentials ;)

**Comment by fit206** [comment]
for my settings it was successful when I pressed the test button but I didn't get any new movie notifications added to my telegram group. I only get the message "Your configuration is correct!".

![Uploading Screenshot 2024-07-04 081117.jpg…]()

**Comment by RomainPierre7** [comment]
Have you correctly check the boxes for "enable notifications for this user", "item movie added" and the subcategories you want ("movie", "serie", "season", "episode", etc).  And don't forget to click on save at the bottom of the page.

Also are your movies well parsed with metadata ? I mean does Jellyfin recognize your movie and give you some metadata on it ?

You can try to run manually the scheduled tasks "refresh library" and "Telegram notifier item added" from dashboard => scheduled tasks.

Try to select more boxes to be notified about (try for example the "session" one and reload you Jellyfin client). Do you receive a message on telegram ?

**Comment by fit206** [comment]
Do you suggest the best metadata for this plugin?

**Comment by Druidblack** [comment]
Good afternoon. If you want to receive a notification in a telegram about adding new content to your library, then I advise you to use https://github.com/Fahmula/jellyfin-telegram-notifier
The program has a more flexible setting for informing about the addition of content.  As a bonus, a youtube link with a movie trailer will be added to each message.

When adding a large number of episodes (TV series), the plugin may start spamming you by sending information about each added episode. And the above program, depending on the setting, will simply inform you about the addition of several seasons of the series.

P.S. I had problems with the speed of downloading metadata for movies, which is why the plugin (and the program) did not find the film cover (it took a little more time to download metadata) and because of the peculiarities of sending messages with a picture in telegrams, the message was not sent. Therefore, I set the scheduler settings to send data for 15 minutes.

**Comment by Druidblack** [comment]
> Do you suggest the best metadata for this plugin? What do you suggest is the best metadata for this plugin? After I checked all the boxes I received a message on telegram saying which platform the user is watching from.

Look at my message. You may have a problem with the metadata download speed. Set the time in the scheduler to 15 minutes. Or turn off the time in the scheduler and after adding the movie to the library, force the task to work with this plugin. You may receive a message with information about the movie.

**Comment by fit206** [comment]
> > Do you suggest the best metadata for this plugin? What do you suggest is the best metadata for this plugin? After I checked all the boxes I received a message on telegram saying which platform the user is watching from.
> 
> Look at my message. You may have a problem with the metadata download speed. Set the time in the scheduler to 15 minutes. Or turn off the time in the scheduler and after adding the movie to the library, force the task to work with this plugin. You may receive a message with information about the movie.

Okay, thanks for your help. I will try.

**Comment by fit206** [comment]
> > Do you suggest the best metadata for this plugin? What do you suggest is the best metadata for this plugin? After I checked all the boxes I received a message on telegram saying which platform the user is watching from.
> 
> Look at my message. You may have a problem with the metadata download speed. Set the time in the scheduler to 15 minutes. Or turn off the time in the scheduler and after adding the movie to the library, force the task to work with this plugin. You may receive a message with information about the movie.

may i know which is the option for me to enter my flask url endpoint in the webhook because there are many options. Sorry, I'm new to creating a server on Jellyfin

**Comment by Druidblack** [comment]
![Безымянный](https://github.com/RomainPierre7/jellyfin-plugin-TelegramNotifier/assets/70659424/59fb32a4-4a23-4585-866d-d6bbe9344782)
You need to specify the ip address where the docker container is installed.
